config:
    environments:
        production:
            target: "https://api.bte.ncats.io"
            phases:
                - duration: 120
                  arrivalRate: 0.5

        local:
            target: "http://localhost:3000"
            phases:
                - duration: 120
                  arrivalRate: 0.5

        dev:
            target: "https://dev.api.bte.ncats.io"
            phases:
                - duration: 120
                  arrivalRate: 0.5
    payload:
        path: "single_hop_examples.csv"
        fields:
            - "input_type"
            - "input_id"
            - "output_type"